reformat and show gd info

diff --git a/Dockerfile-56 b/Dockerfile-56
--- a/Dockerfile-56
+++ b/Dockerfile-56
@@ -21,37 +21,33 @@ ENV DEBIAN_FRONTEND noninteractive
 
 # Install "curl", "libmemcached-dev", "libpq-dev", "libjpeg-dev",
 #         "libpng12-dev", "libfreetype6-dev", "libssl-dev", "libmcrypt-dev",
-RUN set -xe && \
-  apt-get update && \
-  apt-get upgrade -y && \
-  apt-get install -y --no-install-recommends \
-    curl \
-    libmemcached-dev \
-    libz-dev \
-    libpq-dev \
-    libjpeg-dev \
-    libpng-dev \
-    libfreetype6-dev \
-    libssl-dev \
-    libmcrypt-dev
+RUN set -eux; \
+    apt-get update; \
+    apt-get upgrade -y; \
+    apt-get install -y --no-install-recommends \
+            curl \
+            libmemcached-dev \
+            libz-dev \
+            libpq-dev \
+            libjpeg-dev \
+            libpng-dev \
+            libfreetype6-dev \
+            libssl-dev \
+            libmcrypt-dev; \
+    # cleanup
+    rm -rf /var/lib/apt/lists/*
 
-# Install the PHP mcrypt extention
-RUN docker-php-ext-install mcrypt
-
-# Install the PHP pdo_mysql extention
-RUN docker-php-ext-install mysqli \
-    && docker-php-ext-install pdo_mysql
-# Install the PHP pdo_pgsql extention
-RUN docker-php-ext-install pdo_pgsql
-
-#####################################
-# gd:
-#####################################
-
-# Install the PHP gd library
-RUN docker-php-ext-install gd && \
+RUN set -eux; \
+    # Install the PHP mcrypt extention
+    docker-php-ext-install mcrypt; \
+    # Install the PHP pdo_mysql extention
+    docker-php-ext-install pdo_mysql mysqli; \
+    # Install the PHP pdo_pgsql extention
+    docker-php-ext-install pdo_pgsql; \
+    # Install the PHP gd library
     docker-php-ext-configure gd \
-        --enable-gd-native-ttf \
-        --with-jpeg-dir=/usr/lib \
-        --with-freetype-dir=/usr/include/freetype2 && \
-    docker-php-ext-install gd
+            --enable-gd-native-ttf \
+            --with-jpeg-dir=/usr/lib \
+            --with-freetype-dir=/usr/include/freetype2; \
+    docker-php-ext-install gd; \
+    php -r 'var_dump(gd_info());'
