check matrix jobs

diff --git a/.github/workflows/dockerimage.yml b/.github/workflows/dockerimage.yml
--- a/.github/workflows/dockerimage.yml
+++ b/.github/workflows/dockerimage.yml
@@ -55,3 +55,15 @@ jobs:
           platforms: linux/arm64
           push: ${{ (github.event_name != 'pull_request') && (github.repository == 'laradock/php-fpm') && (github.ref == 'refs/heads/master') }}
           tags: ${{ steps.meta.outputs.tags }}
+
+  final_check:
+    runs-on: ubuntu-latest
+    needs: build
+    if: always()
+    steps:
+      - name: Fail if any matrix job failed
+        run: |
+          if [ "${{ needs.build.result }}" == "failure" ]; then
+            echo "Some matrix jobs failed, marking workflow as failed."
+            exit 1
+          fi
